<?PHP
#-----------------------------------------------------------------------------------------
# US ENGLISH LANGUAGE FILE FOR PWA+PHP
#-----------------------------------------------------------------------------------------
$LANG_MISSING_VAR_H1="Error: One or more required variables is missing from config.php!";
$LANG_MISSING_VAR_H3="Please re-run the install.php configuration script.";
$LANG_PERM_FILTER="Permission Denied.  Filter is required.";
$LANG_GALLERIES="Picasa Galleries";
$LANG_GALLERY="Gallery";
$LANG_IMAGES="images";
$LANG_PRIVATE="Private";
$LANG_PUBLIC="Public";
$LANG_WHERE="Location";
$LANG_ACCESS="Access";
$LANG_PHOTOS_IN="photos in";
$LANG_ALBUMS="albums";
$LANG_BACK="back to album list";
$LANG_PAGE="Page";
$LANG_GET="Get";
$LANG_GENERATED="Page generated by";
?>
